### ISSUE TITLE
Unit test question

### ISSUE THREAD

**Issue by victorrodrigueznadq** [oracle-samples/clara-rules#495]
I'm writing some unit test for my clara rules, however, I only want to test one rule at a time.  This is how I'm creating my session:

```
(def fresh-session (-> (mk-session 'com.nasdaq.rms.rules.nqe.transactional.accumulations.nqe-rms-accumulation-rules-xlsx)
                       ;; insert BillingDates for use in session
                       (insert jan-2024-billing-dates)))
```

When I create the session, is there a way that I can load only one rule?  Or maybe unload all but the rule I'm testing?  The above will load all the rules in the specified package.  Hoping to be able to just load one at a time for testing.  Thanks!

**Comment by EthanEChristian** [comment]
@victorrodrigueznadq, 
yes the `mk-session` macro supports the idea of loading rules piecemeal. 
For instance, you should be able to load a session using something like:
```clojure
(ns some-namespace
  (:require [clara.rules :as r]))

(r/defrule a-rule
  [?o <- Object]
  =>
  (println ?o))
```
```clojure
(ns test-some-namespace
 (:require 
   [clara.rules :as r] 
   [some-namespace :as subject]))
   
 (def session 
   (-> (r/mk-session [subject/a-rule])
         (r/insert <items>)
         (r/fire-rules)))
```

I will note that `mk-session` also supports a data contract of using the same pattern:
```
(r/mk-session 
  [{:ns-name 'some-namespace,
     :lhs [{:type java.lang.Object, :constraints [], :fact-binding :?o}],
     :rhs `(do (println ~'?o)),
     :name "some-namespace/a-rule"}])
```
in the off chance that you might want to generate rules on the fly.

**Comment by victorrodrigueznadq** [comment]
thanks @EthanEChristian !  is the r/ syntax required?  I'm currently not using that syntax.

**Comment by EthanEChristian** [comment]
@victorrodrigueznadq, no [aliasing](https://clojuredocs.org/clojure.core/alias) isn't required. It usually comes down to style preference, unless two namespaces would have overlapping var definitions.

I tend to lean towards alias over refer as I feel it lends to the readability of larger files, and allows for easier distinction of locally defined vars versus those that are imported.

**Comment by victorrodrigueznadq** [comment]
@EthanEChristian sounds good.  is there anything I have to do to destroy/unallocate/clear a session so that there's no danger of test intermingling their sessions?
