### ISSUE TITLE
Does Clara support these Drools behaviors?

### ISSUE THREAD

**Issue by victorrodrigueznadq** [oracle-samples/clara-rules#497]
Does clara support these drools behaviors?

![Screenshot 2024-05-20 at 6 24 55 AM](https://github.com/oracle-samples/clara-rules/assets/123778776/b757dea4-d4e0-4ce4-a002-1a01995df76b)

![Screenshot 2024-05-20 at 6 25 20 AM](https://github.com/oracle-samples/clara-rules/assets/123778776/43d889ff-d645-4582-9a96-ebcde7ada006)

**Comment by EthanEChristian** [comment]
@victorrodrigueznadq, 
Clara supports [Conditional negation](https://www.clara-rules.org/docs/expressions/#boolean-expressions), using the drools example as inspiration we'd arrive at a rule like:
```clojure
(r/defrule not-a-bus
  [:not [Bus]]
  =>
  (r/insert (->NoBusses)))
```
or 
```clojure
(r/defrule no-red-busses
  [:not [Bus (= color "red")]]
  =>
  (r/insert (->NoRedBusses)))
```

Clara also supports the idea of `exists` as well,  `:exists` is a syntactic sugar around a basic accumulator [exists](https://www.clara-rules.org/apidocs/0.21.1/clojure/clara.rules.accumulators.html#var-all). Used something like:
```clojure
(r/defrule got-bus
  [:exists [Bus]]
  =>
  (r/insert (->BusExists)))
```
or
```clojure
 (r/defrule got-red-bus
  [:exists [Bus (= color "red")]]
  =>
  (r/insert (->RedBusExists)))
```

**Comment by victorrodrigueznadq** [comment]
thanks @EthanEChristian
