### ISSUE TITLE
Effect of cache...

### ISSUE THREAD

**Issue by ghost** [oracle-samples/clara-rules#73]
Hi,

finally made my mind about the problem I described yesterday (or the day before ? Lost track of time a bit :) on the mailing list.

I have a simple rule space to merge facts from two different sources. Nothing fancy here.
The two first rules do not even have conditions to meet to activate. It's taking a fact which is always present, the subscriber fact. The second one is taking a bunch of other facts (regions) always present and wraps them all.
The top of the rule name space reads like this:

(defrecord MergedFact [fact])
(defrule encapsuler-abonnés
  [?abonne <- DistAbonne]
  =>
  (insert! (->MergedFact ?abonne)))

(defrule lier-regions
  [?offre-region <- OffreRegion]
  =>
  (doseq [r (ajouter-regions  ?offre-region)](insert! %28->MergedFact r%29)))
...
Pretty straightforward no ? I would expect these two rules to systematically fire as soon as these fact types are present. I maybe wrong :) 

I run this merge operation on every facts bundle for each subscriber in separate (new) sessions.
The subscriber and region facts are always present (dumped them to a subscriber specific file before session insert to check).
I run the first subscriber session with cache disabled as I want to make sure that any changes will be picked up (this will run in prod as a non stop service).
The following subscribers never get their rules fired with the cache set to its default (true).

When querying with the cache enabled I get the following Exception:

2014-12-25 04:47:53,822 ERROR maskatel.cerbere.rules.merge - Cannot return MergedFacts - Context: {session #<LocalSession clara.rules.engine.LocalSession@6106e055>, e# #<IllegalArgumentException java.lang.IllegalArgumentException: The query {:name "maskatel.cerbere.rules.merge/merged-facts", :lhs [{:fact-binding :?new-facts, :type maskatel.cerbere.rules.merge.MergedFact, :constraints []}], :params #{}} is invalid or not included in the rule base.>}
java.lang.IllegalArgumentException: The query {:name "maskatel.cerbere.rules.merge/merged-facts", :lhs [{:fact-binding :?new-facts, :type maskatel.cerbere.rules.merge.MergedFact, :constraints []}], :params #{}} is invalid or not included in the rule base.
    at clara.rules.platform$throw_error.invoke(platform.clj:4)
    at clara.rules.engine.LocalSession.query(engine.clj:810)
    at clara.rules$query.doInvoke(rules.clj:49)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at maskatel.cerbere.rules.merge$query_results$fn__29766.invoke(merge.clj:71)
    at maskatel.cerbere.rules.merge$query_results.invoke(merge.clj:71)
    at clojure.lang.Var.invoke(Var.java:379)
    at maskatel.cerbere.rules.engine$run.doInvoke(engine.clj:63)
    at clojure.lang.RestFn.invoke(RestFn.java:521)

Which seems to indicate that no insert! ever occurred at least for the first two rules.
If I run the merge rules on the other subscribers with cache set to false, tadam ! I get merged facts every time.

Worse, when I rerun the first subscriber in the same REPL session without the cache, it ends up with no merged facts to return and hits the same exception.

Comparing the trace files from Clara with/without the cache enabled does not show any differences for a given subscriber until you hit the query section. 
The inspection with the explanations looks the same also until you get to the query part.
No rhs seems to be executing when the cache is being used...

I am using this nice parallel graphic meld tool and the only greenish portion is the query detail dump.

The query stuff is at the bottom of the rule name space and looks like this:

(defn query-results
  [session](let [wrapped-facts %28try %28query session merged-facts%29 %28catch Exception e# %28log/error %28format) e#) []))
        facts (-> (into [](remove nil? %28mapcat #%28map :fact %28vals %%29%29 wrapped-facts%29)))]
    (combine-queries (return-facts facts))))

This fn is called from the name space that processes all subscriber facts bundles. 
Now it resides in the same name space as the rules. Is this a mistake ? Should I place it in a separate name space (this is my next test) ?

Or am I doing anything wrong here on how I express he query ?

I can provide more details through an off issue channel (privacy restrictions) but from the diagnosis available from the inspect and the trace name spaces there's not much that can be told.
If the rule triggering traces are the same with/without the cache there's something I am missing
but do not have a clue about what is going on.

I will try to split the query in its own name space to see if it changes anything.

Meanwhile I can run in parallel with the cache disabled for all subscribers, the impact is mitigated in the short term, my next delivery date will not be compromised.

Maybe it's something obvious. I reread the examples but can't seem to find anything odd compared to what I am doing in my code base.

Thank you,

Yeah I know it's xmas and you are all wondering what I am doing here at 5 am :)
Got fed up about the xmas thing, here in Morocco I hardly see any xmas frenesy, it's a day almost like any other day except a bit quieter that's it.

Relaxing :)

**Comment by rbrush** [comment]
The permgen is likely growing because Clara generates rule code using
Clojure's eval, which will generate new function classes on the fly. I
don't know if there is a way around this prior to Java 8, but we could
mitigate it by caching generated functions that are unchanged between rule
reloads. This way if only a small number of rules change during a reload,
we don't regenerate a lot of functions. This should also help the
performance of reloading rule sets.

I logged an issue to track this:
https://github.com/rbrush/clara-rules/issues/77
